# Generated by Django 4.0.1 on 2022-01-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ano', models.DateField()),
                ('duracao', models.IntegerField()),
                ('tipo', models.CharField(choices=[('S', 'Serie'), ('F', 'Filme')], max_length=1)),
                ('categoria', models.CharField(choices=[('T', 'Terror'), ('C', 'Comedia'), ('A', 'Animação'), ('AV', 'Aventura'), ('AC', 'Ação')], default='', max_length=2)),
            ],
        ),
    ]
