# Generated by Django 4.0.1 on 2022-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='ano',
            new_name='data_lancamento',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='nome',
            new_name='titulo',
        ),
    ]
